### ISSUE TITLE
Macros screen is empty

### ISSUE THREAD

**Issue by TypicallyThomas** [IsThisMyRealName/too-many-tokens-dnd#6] opened 2024-07-24 08:42 UTC
I'm still on V11. When I open the Macro compendium, there's nothing in there. I am fairly new to these content pack modules, so maybe I am simply doing something wrong, but I don't see any part where I can use the module
![image](https://github.com/user-attachments/assets/8ec54019-628c-4ef2-a733-3adae5abed61)

**Comment by IsThisMyRealName** [comment] 2024-07-29 05:50
That's strange. My first guess is that it's because of the V11, but I will have to look into that. For now you can also find the macro here:
https://github.com/IsThisMyRealName/too-many-tokens-dnd/blob/main/TooManyTokensMacro.js

**Comment by NickRimer03** [comment] 2024-08-30 23:43
Hi there! I have the same problem, Macro Compendium is empty. Everything worked properly, but after some updates (I think) it became empty on V11. And it's still empty on V12.

I use your script manually from macro bar, but it seems that it doesn't work properly.

Typical example is Commoner. I ask script for Commoner-Human-Urban-Male, but it can easily change picture for Commoner-HalfOrc-Arctic-Female. It's just a random result, no system. You will get what you want or you will have dozens of tries. It's uncomfortable and creates funny situations sometimes during the game. But I don't want them to be so funny, and it's takes a lot of time to select unique token manually.

How the script can be fixed to avoid such a problem?

**Comment by IsThisMyRealName** [comment] 2024-08-31 17:31
I am sorry, I am not able to reproduce this error. My only guesses at the moment are to reinstall the module, hopefully that fixes everything and if not make sure to use the macro from here:
https://github.com/IsThisMyRealName/too-many-tokens-dnd/blob/main/TooManyTokensSelectMacro.js

If all that still doesn't help can you check, what exactly gets applied as the image path for the token and if you press "F12" in foundry are there any error messages in the console, when using the macro?

As a temporary fix you can copy the path from https://toomanytokens.com/index.html?system=dnd&name=Commoner&tags=Human~Urban~Male and use that for your tokens. I know that's not ideal and I will try to reproduce/fix this error.

**Comment by IsThisMyRealName** [comment] 2024-11-09 08:38
Closed for now, maybe it is fixed by fixing capitalization.

**Closed as completed** 2024-11-09 08:37 UTC
